### PR TITLE
Fix for newer pudb version

### PR DESCRIPTION
**Pull request by AntoineD**
Mimics last nose-pdb plugin.

### CODE REVIEW

**Comment by AntoineD** [comment]
Hi, any chance to get that request pulled?

**Comment by chriswl** [comment]
+1

**Comment by wesm** [comment]
+1

**Comment by momijiame** [comment]
+1

**Comment by AntoineD** [comment]
@akaihola, from your github activity it looks like you're still around, and you show no more interest or time to maintain that plugin.
Would you mind to transfer its responsibility to me so I can update pypi?

**Comment by akaihola** [comment]
@AntoineD You seem to have owner role for this package [on PyPI](https://pypi.python.org/pypi?:action=role_form&package_name=nose-pudb). Everything ok?

**Comment by AntoineD** [comment]
@akaihola, I hope that you understand why I have asked (co-)ownership on PyPI, and that it is OK for you.

**Comment by akaihola** [comment]
Yes, it's perfectly ok for me! Thanks for adopting it!

**Pull request merged**
